######################################################################
# Automatically generated by qmake (3.0) ?? 20. ??? 14:46:50 2013
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets
