CCC=g++
FLAGS= -Wall -Wextra -Werror -O3 -std=c++98 -pedantic
NAME=curiously-recurring-template-pattern
SOURCES=main.cpp

all:	$(SOURCES)
	$(CCC) $(FLAGS) -o $(NAME) $(SOURCES)

clean:
	git clean -dfX
