#ifndef DECLARATIONS_H
#define DECLARATIONS_H

void AlgorithmsImprovements();
void Alignment();
void Array();
void Async();
void Attributes();
void AutoTypeDeduction();
void BinaryLiterals();
void C99features();
void ConstExpr();
void ContainerImprovements();
void ControlOfDefaults();
void CopyingExceptions();
void DeclType();
void DelegatingConstructors();
void EnumClass();
void ExplicitConversionOperators();
void ExternTemplates();
void ForwardList();
void FunctionAndBind();
void FutureAndPromise();
void GeneralizedPODs();
void GeneralizedUnions();
void InClassMemberInitializers();
void InheritedConstructors();
void InitializerLists();
void InlineNamespace();
void Lambdas();
void LocalTypes();
void Locks();
void LongLong();
void MoveNotCopy();
void MutualExclusion();
void NoExcept();
void NullPtr();
void OverrideControl();
void PreventingNarrowing();
void RandomNumberGeneration();
void RangeForStatement();
void RawStringLiterals();
void RegularExpressions();
void RightAngleBrackets();
void RValueReferences();
void SharedPtr();
void StaticAssertions();
void SuffixReturnTypeSyntax();
void TemplateAlias();
void Threads();
void TimeUtilities();
void Tuple();
void UniformInitialization();
void UniquePtr();
void UnorderedContainers();
void UserDefinedLiterals();
void VariadicTemplates();

#endif // DECLARATIONS_H
